// frontend/src/app/(auth)/login/page.tsx
"use client";

import Link from "next/link";
import { useRouter, useSearchParams } from "next/navigation";
import { useTheme } from "next-themes";
import { useEffect, useState } from "react";

import { RememberSessionOption } from "@/components/auth/remember-session-option";
import { Button } from "@/components/ui/button";
import { FlickeringGrid } from "@/components/ui/flickering-grid";
import { Input } from "@/components/ui/input";
import { useAuth } from "@/core/auth/AuthProvider";
import { resolveAuthNextPath } from "@/core/auth/next-path";
import {
  loadRememberLoginPreference,
  saveRememberLoginPreference,
} from "@/core/auth/remember-login";
import {
  canCreateRegularAccount,
  fetchSetupStatus,
  type SetupStatusResponse,
} from "@/core/auth/setup";
import { parseAuthError } from "@/core/auth/types";
import { useI18n } from "@/core/i18n/hooks";

export default function LoginPage() {
  const router = useRouter();
  const searchParams = useSearchParams();
  const { isAuthenticated } = useAuth();
  const { theme, resolvedTheme } = useTheme();
  const { t } = useI18n();

  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");
  const [rememberMe, setRememberMe] = useState(true);
  const [isLogin, setIsLogin] = useState(true);
  const [ssoProviders, setSsoProviders] = useState<
    { id: string; display_name: string; type: string }[]
  >([]);
  const [setupStatus, setSetupStatus] = useState<SetupStatusResponse | null>(
    null,
  );
  const [setupStatusPhase, setSetupStatusPhase] = useState<
    "checking" | "ready" | "unavailable"
  >("checking");
  const [setupStatusAttempt, setSetupStatusAttempt] = useState(0);

  // Extract error from query params (e.g., ?error=sso_failed)
  const errorParam = searchParams.get("error");
  const [error, setError] = useState(
    errorParam
      ? (t.login.errors[errorParam as keyof typeof t.login.errors] ??
          t.login.authFailed)
      : "",
  );
  // Soft hint shown after a failed login when SSO is configured: an SSO-only
  // account has no local password, so the backend returns a generic
  // "incorrect email or password" (deliberately, to avoid account enumeration).
  // Nudge the user toward the SSO buttons without confirming the account exists.
  const [showSsoHint, setShowSsoHint] = useState(false);
  const [loading, setLoading] = useState(false);

  // Get next parameter for validated redirect
  const nextParam = searchParams.get("next");
  const redirectPath = resolveAuthNextPath(nextParam);
  const regularSignupAllowed = canCreateRegularAccount({
    // A failed probe must not expose registration while the system's setup
    // state is unknown. Existing users can still sign in normally.
    checked: setupStatusPhase === "ready",
    status: setupStatus,
  });
  const systemNeedsAdminSetup = setupStatus?.needs_setup === true;
  const showSetupStatusUnavailable =
    setupStatusPhase === "unavailable" ||
    (setupStatusAttempt > 0 && setupStatusPhase === "checking");

  // Redirect if already authenticated (client-side, post-login)
  useEffect(() => {
    if (isAuthenticated) {
      router.push(redirectPath);
    }
  }, [isAuthenticated, redirectPath, router]);

  useEffect(() => {
    const preference = loadRememberLoginPreference();
    setRememberMe(preference.rememberMe);
    if (preference.email) {
      setEmail(preference.email);
    }
  }, []);

  // Fetch setup state independently so retrying a slow Gateway does not also
  // refetch unrelated auth-provider configuration.
  useEffect(() => {
    let cancelled = false;
    setSetupStatusPhase("checking");

    void fetchSetupStatus()
      .then((data) => {
        if (cancelled) return;
        setSetupStatus(data);
        setSetupStatusPhase("ready");
        if (data.needs_setup) {
          setIsLogin(true);
        }
      })
      .catch(() => {
        if (!cancelled) {
          setSetupStatus(null);
          setSetupStatusPhase("unavailable");
        }
      });

    return () => {
      cancelled = true;
    };
  }, [setupStatusAttempt]);

  // SSO providers are static for the page lifetime and should not be coupled to
  // setup-status retries.
  useEffect(() => {
    let cancelled = false;

    void fetch("/api/v1/auth/providers")
      .then((r) => r.json())
      .then(
        (data: {
          providers: { id: string; display_name: string; type: string }[];
        }) => {
          if (!cancelled) {
            setSsoProviders(data.providers ?? []);
          }
        },
      )
      .catch(() => {
        // Ignore errors; no SSO providers shown
      });

    return () => {
      cancelled = true;
    };
  }, []);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setError("");
    setShowSsoHint(false);
    setLoading(true);

    if (!isLogin && !regularSignupAllowed) {
      setError(t.login.adminSetupRequiredDescription);
      setLoading(false);
      return;
    }

    try {
      const endpoint = isLogin
        ? "/api/v1/auth/login/local"
        : "/api/v1/auth/register";
      const body = isLogin
        ? new URLSearchParams({
            password,
            remember_me: String(rememberMe),
            username: email,
          })
        : JSON.stringify({ email, password, remember_me: rememberMe });

      const headers: HeadersInit = isLogin
        ? { "Content-Type": "application/x-www-form-urlencoded" }
        : { "Content-Type": "application/json" };

      const res = await fetch(endpoint, {
        method: "POST",
        headers,
        body,
        credentials: "include", // Important: include HttpOnly cookie
      });

      if (!res.ok) {
        const data = await res.json();
        const authError = parseAuthError(data);
        setError(authError.message);
        // On a failed login with SSO configured, surface a hint pointing at the
        // SSO buttons — the "wrong password" may really mean "this is an SSO account".
        if (isLogin && ssoProviders.length > 0) {
          setShowSsoHint(true);
        }
        return;
      }

      saveRememberLoginPreference({ email, rememberMe });

      // Both login and register set a cookie — redirect to workspace
      router.push(redirectPath);
    } catch {
      setError(t.login.networkError);
    } finally {
      setLoading(false);
    }
  };

  const actualTheme = theme === "system" ? resolvedTheme : theme;

  return (
    <div className="bg-background relative flex min-h-screen items-center justify-center overflow-x-hidden overflow-y-auto">
      <FlickeringGrid
        className="absolute inset-0 z-0 mask-[url(/images/deer.svg)] mask-size-[100vw] mask-center mask-no-repeat md:mask-size-[72vh]"
        squareSize={4}
        gridGap={4}
        color={actualTheme === "dark" ? "white" : "black"}
        maxOpacity={0.3}
        flickerChance={0.25}
      />
      <div className="border-border/20 bg-background/5 w-full max-w-md space-y-6 rounded-3xl border p-8 backdrop-blur-sm">
        <div className="text-center">
          <h1 className="text-foreground font-serif text-3xl">DeerFlow</h1>
          <p className="text-muted-foreground mt-2">
            {isLogin ? t.login.signInTitle : t.login.createAccountTitle}
          </p>
        </div>

        {showSetupStatusUnavailable && (
          <div
            role="status"
            aria-live="polite"
            className="border-l-2 border-amber-500 ps-3 text-sm"
          >
            <p className="font-medium">{t.login.serviceUnavailableTitle}</p>
            <p className="text-muted-foreground mt-1">
              {t.login.serviceUnavailableDescription}
            </p>
            <Button
              type="button"
              variant="outline"
              size="sm"
              className="mt-3"
              disabled={setupStatusPhase === "checking"}
              onClick={() => {
                setSetupStatusPhase("checking");
                setSetupStatusAttempt((attempt) => attempt + 1);
              }}
            >
              {setupStatusPhase === "checking"
                ? t.login.pleaseWait
                : t.login.retry}
            </Button>
          </div>
        )}

        {systemNeedsAdminSetup && (
          <div className="border-l-2 border-blue-500 ps-3 text-sm">
            <p className="font-medium">{t.login.adminSetupRequiredTitle}</p>
            <p className="text-muted-foreground mt-1">
              {t.login.adminSetupRequiredDescription}
            </p>
            <Link
              href="/setup"
              className="mt-2 inline-block font-medium text-blue-500 hover:underline"
            >
              {t.login.createAdminAccount}
            </Link>
          </div>
        )}

        <form onSubmit={handleSubmit} className="space-y-2">
          <div className="flex flex-col space-y-1">
            <label htmlFor="email" className="text-sm font-medium">
              {t.login.email}
            </label>
            <Input
              id="email"
              type="email"
              value={email}
              onChange={(e) => setEmail(e.target.value)}
              placeholder={t.login.emailPlaceholder}
              required
            />
          </div>
          <div className="flex flex-col space-y-1">
            <label htmlFor="password" className="text-sm font-medium">
              {t.login.password}
            </label>
            <Input
              id="password"
              type="password"
              value={password}
              onChange={(e) => setPassword(e.target.value)}
              placeholder={t.login.passwordPlaceholder}
              required
              minLength={isLogin ? 6 : 8}
            />
          </div>

          <RememberSessionOption
            checked={rememberMe}
            onCheckedChange={setRememberMe}
          />

          {error && <p className="text-destructive text-sm">{error}</p>}

          <Button type="submit" className="w-full" disabled={loading}>
            {loading
              ? t.login.pleaseWait
              : isLogin
                ? t.login.signIn
                : t.login.createAccount}
          </Button>
        </form>

        {ssoProviders.length > 0 && (
          <div className="space-y-2">
            {isLogin && (
              <div className="relative my-4">
                <div className="absolute inset-0 flex items-center">
                  <span className="w-full border-t" />
                </div>
                <div className="relative flex justify-center text-xs uppercase">
                  <span className="bg-background text-muted-foreground px-2">
                    {t.login.orContinueWith}
                  </span>
                </div>
              </div>
            )}
            {showSsoHint && (
              <p className="text-muted-foreground text-center text-sm">
                {t.login.ssoHint}
              </p>
            )}
            {ssoProviders.map((provider) => (
              <Button
                key={provider.id}
                type="button"
                variant="outline"
                className="w-full"
                disabled={loading}
                onClick={() => {
                  window.location.href = `/api/v1/auth/oauth/${provider.id}?next=${encodeURIComponent(redirectPath)}&remember_me=${String(rememberMe)}`;
                }}
              >
                {t.login.continueWith(provider.display_name)}
              </Button>
            ))}
          </div>
        )}

        {regularSignupAllowed && (
          <div className="text-center text-sm">
            <button
              type="button"
              onClick={() => {
                setIsLogin(!isLogin);
                setError("");
                setShowSsoHint(false);
              }}
              className="text-blue-500 hover:underline"
            >
              {isLogin ? t.login.noAccountSignUp : t.login.haveAccountSignIn}
            </button>
          </div>
        )}

        <div className="text-muted-foreground text-center text-xs">
          <Link href="/" className="hover:underline">
            {t.login.backToHome}
          </Link>
        </div>
      </div>
    </div>
  );
}

// frontend-vue/app/pages/login.vue
<!--
  【文件职责】     完整本地登录/注册、SSO 入口与 setup-status fail-closed 恢复。
  【架构位置】     L3 auth surface
  【主要导出】     默认 login page
  【依赖关系】     Gateway auth/setup APIs · auth layout
  【边界与注意】   回跳必须经过 resolveAuthNextPath；未知 setup 状态不得开放注册。
-->

<script setup lang="ts">
import { computed, onMounted, ref, watch } from "vue";
import { useQueryClient } from "@tanstack/vue-query";

import { Button } from "@/components/ui/button";
import FlickeringGrid from "@/components/ui/effects/FlickeringGrid.vue";
import { Input } from "@/components/ui/input";
import { clearAuthenticatedClientState } from "@/core/auth/client-state";
import { resolveAuthNextPath } from "@/core/auth/next-path";
import {
  loadRememberLoginPreference,
  saveRememberLoginPreference,
} from "@/core/auth/remember-login";
import {
  canCreateRegularAccount,
  fetchSetupStatus,
  type SetupStatusResponse,
} from "@/core/auth/setup";
import { parseAuthError } from "@/core/auth/types";

definePageMeta({ layout: "auth" });

type Provider = { id: string; display_name: string; type: string };

const route = useRoute();
const { $i18n } = useNuxtApp();
const queryClient = useQueryClient();
const email = ref("");
const password = ref("");
const rememberMe = ref(true);
const isLogin = ref(true);
const providers = ref<Provider[]>([]);
const setupStatus = ref<SetupStatusResponse | null>(null);
const setupPhase = ref<"checking" | "ready" | "unavailable">("checking");
const setupAttempt = ref(0);
const error = ref(
  typeof route.query.error === "string" ? $i18n.t.value.login.authFailed : "",
);
const showSsoHint = ref(false);
const loading = ref(false);

const redirectPath = computed(() =>
  resolveAuthNextPath(
    typeof route.query.next === "string"
      ? route.query.next
      : typeof route.query.redirect === "string"
        ? route.query.redirect
        : null,
  ),
);
const signupAllowed = computed(() =>
  canCreateRegularAccount({
    checked: setupPhase.value === "ready",
    status: setupStatus.value,
  }),
);
const setupUnavailable = computed(
  () =>
    setupPhase.value === "unavailable" ||
    (setupAttempt.value > 0 && setupPhase.value === "checking"),
);

async function checkSetupStatus() {
  setupPhase.value = "checking";
  try {
    setupStatus.value = await fetchSetupStatus();
    setupPhase.value = "ready";
    if (setupStatus.value.needs_setup) isLogin.value = true;
  } catch {
    setupStatus.value = null;
    setupPhase.value = "unavailable";
  }
}

async function submit() {
  error.value = "";
  showSsoHint.value = false;
  if (!isLogin.value && !signupAllowed.value) {
    error.value = $i18n.t.value.login.adminSetupRequiredDescription;
    return;
  }

  loading.value = true;
  try {
    const endpoint = isLogin.value
      ? "/api/v1/auth/login/local"
      : "/api/v1/auth/register";
    const response = await fetch(endpoint, {
      method: "POST",
      credentials: "include",
      headers: {
        "Content-Type": isLogin.value
          ? "application/x-www-form-urlencoded"
          : "application/json",
      },
      body: isLogin.value
        ? new URLSearchParams({
            username: email.value,
            password: password.value,
            remember_me: String(rememberMe.value),
          })
        : JSON.stringify({
            email: email.value,
            password: password.value,
            remember_me: rememberMe.value,
          }),
    });
    if (!response.ok) {
      error.value = parseAuthError(await response.json()).message;
      showSsoHint.value = isLogin.value && providers.value.length > 0;
      return;
    }
    clearAuthenticatedClientState(queryClient);
    saveRememberLoginPreference({
      email: email.value,
      rememberMe: rememberMe.value,
    });
    await navigateTo(redirectPath.value);
  } catch {
    error.value = $i18n.t.value.login.networkError;
  } finally {
    loading.value = false;
  }
}

function startSso(provider: Provider) {
  window.location.assign(
    `/api/v1/auth/oauth/${encodeURIComponent(provider.id)}?next=${encodeURIComponent(redirectPath.value)}&remember_me=${String(rememberMe.value)}`,
  );
}

/*
  已经有 session 的人不该停在登录页上——上游 login/page.tsx:77 的
  `if (isAuthenticated) router.push(redirectPath)`。它不只是「刚登录完的那一跳」：
  **关掉鉴权部署时（`authDisabled`），Gateway 直接给出一个用户**，于是上游访问
  /login 会立刻回到工作区，而本仓停在一张永远也用不上的登录表单上。
  实测（2026-09-02 probe）两个应用在同一份配置下一个跳一个不跳，台账口径下差 58 行。

  判据与上游一致：**只看「有没有 user」**（React 的 `isAuthenticated = user !== null`），
  不看 authDisabled 开关——`unavailable` 是服务状态不是登出，那一支要留在登录页上。

  **session query 必须动态 import**，与 middleware/auth.global.ts 同一条理由：
  `session-query` → `session` → `auth/types` 拖着 zod 与 vue-query 的一整块。
  第一版在这里写了静态 `useAuthSession`，`/login` 的关键路径当场从 348 KB 涨到
  **728 KB**（route-payload 门禁抓的）。走 queryClient 拿的还是同一份缓存，
  与 middleware、`/auth/callback` 共用一个 query key。
*/
async function redirectIfSignedIn() {
  const { authSessionQueryOptions } = await import("@/core/auth/session-query");
  const probe = await queryClient.fetchQuery(authSessionQueryOptions());
  if (probe.tag === "authenticated") await navigateTo(redirectPath.value);
}

watch(setupAttempt, () => void checkSetupStatus(), { immediate: true });
onMounted(() => {
  void redirectIfSignedIn();
  const preference = loadRememberLoginPreference();
  email.value = preference.email;
  rememberMe.value = preference.rememberMe;
  void fetch("/api/v1/auth/providers", { credentials: "include" })
    .then((response) => (response.ok ? response.json() : { providers: [] }))
    .then((data: { providers?: Provider[] }) => {
      providers.value = data.providers ?? [];
    })
    .catch(() => undefined);
});
</script>

<template>
  <div
    class="relative flex min-h-screen w-full items-center justify-center overflow-hidden p-4"
  >
    <FlickeringGrid
      class="absolute inset-0 z-0 text-black opacity-35 [mask:url('/images/deer.svg')_center/100vw_no-repeat] md:[mask-size:72vh] dark:text-white"
      :square-size="4"
      :grid-gap="4"
      color="currentColor"
      :max-opacity="0.3"
      :flicker-chance="0.25"
    />
    <section
      class="bg-background/85 border-border/50 relative z-10 w-full max-w-md space-y-6 rounded-3xl border p-8 shadow-xl backdrop-blur-sm"
    >
      <header class="text-center">
        <h1 class="font-serif text-3xl">DeerFlow</h1>
        <p class="text-muted-foreground mt-2">
          {{
            isLogin
              ? $i18n.t.value.login.signInTitle
              : $i18n.t.value.login.createAccountTitle
          }}
        </p>
      </header>

      <div
        v-if="setupUnavailable"
        role="status"
        aria-live="polite"
        class="border-l-2 border-amber-500 ps-3 text-sm"
      >
        <p class="font-medium">
          {{ $i18n.t.value.login.serviceUnavailableTitle }}
        </p>
        <p class="text-muted-foreground mt-1">
          {{ $i18n.t.value.login.serviceUnavailableDescription }}
        </p>
        <!--
          上游 `(auth)/login/page.tsx:232` 是
          `<Button variant="outline" size="sm" className="mt-3">`。手写那版只留了
          `border`：少 `hover:bg-accent hover:text-accent-foreground`（悬停无反应）、
          少 `cursor-pointer`、少 3px 焦点环、少 `shadow-xs` 与那三条
          `dark:*`，尺寸也差一档（sm 是 `h-8 px-3 gap-1.5`，手写那版是
          `px-3 py-1.5` 没有固定高度）。
        -->
        <Button
          type="button"
          variant="outline"
          size="sm"
          class="mt-3"
          :disabled="setupPhase === 'checking'"
          @click="setupAttempt += 1"
        >
          {{
            setupPhase === "checking"
              ? $i18n.t.value.login.pleaseWait
              : $i18n.t.value.login.retry
          }}
        </Button>
      </div>

      <div
        v-if="setupStatus?.needs_setup"
        class="border-l-2 border-blue-500 ps-3 text-sm"
      >
        <p class="font-medium">
          {{ $i18n.t.value.login.adminSetupRequiredTitle }}
        </p>
        <p class="text-muted-foreground mt-1">
          {{ $i18n.t.value.login.adminSetupRequiredDescription }}
        </p>
        <NuxtLink
          to="/setup"
          class="mt-2 inline-block font-medium text-blue-500 hover:underline"
          >{{ $i18n.t.value.login.createAdminAccount }}</NuxtLink
        >
      </div>

      <!--
        表单里的每一个控件都走 **primitive**，不手写 class。
        wave 68 用 `make dom-parity` 的几何档量出来，这一页此前**系统性地绕过了
        L2 层**：输入框是裸 `<input class="… px-3 py-2">`（实测 h 42 / 字号 16px，
        而上游的 `<Input>` 是 `h-9` + `md:text-sm` → h 36 / 14px），提交键与 SSO 键
        是裸 `<button>`，勾选框只有 `mt-1`（13px，上游是 `h-4 w-4` = 16px）。
        绕过 primitive 丢掉的不只是尺寸——焦点环、`aria-invalid` 态、深色模式、
        禁用态全都不再跟着 L2 走。

        字段分组 `flex flex-col space-y-1` 与 form 的 `space-y-2` 也照上游
        （frontend/src/app/(auth)/login/page.tsx:265）；本仓原来没有分组容器、
        form 用的是 `space-y-3`。
      -->
      <form class="space-y-2" @submit.prevent="submit">
        <div class="flex flex-col space-y-1">
          <label class="text-sm font-medium" for="email">{{
            $i18n.t.value.login.email
          }}</label>
          <Input
            id="email"
            v-model="email"
            type="email"
            autocomplete="email"
            required
            :placeholder="$i18n.t.value.login.emailPlaceholder"
          />
        </div>
        <div class="flex flex-col space-y-1">
          <label class="text-sm font-medium" for="password">{{
            $i18n.t.value.login.password
          }}</label>
          <Input
            id="password"
            v-model="password"
            type="password"
            :autocomplete="isLogin ? 'current-password' : 'new-password'"
            required
            :minlength="isLogin ? 6 : 8"
            :placeholder="$i18n.t.value.login.passwordPlaceholder"
          />
        </div>
        <!--
          与上游 RememberSessionOption 逐字同构
          （frontend/src/components/auth/remember-session-option.tsx:17）。
        -->
        <label class="text-muted-foreground flex items-start gap-2 text-sm">
          <input
            v-model="rememberMe"
            type="checkbox"
            class="border-input mt-1 h-4 w-4 rounded"
          />
          <span>
            <span class="text-foreground block font-medium">{{
              $i18n.t.value.login.rememberMe
            }}</span>
            <span>{{ $i18n.t.value.login.rememberMeDescription }}</span>
          </span>
        </label>
        <p v-if="error" role="alert" class="text-destructive text-sm">
          {{ error }}
        </p>
        <Button type="submit" class="w-full" :disabled="loading">
          {{
            loading
              ? $i18n.t.value.login.pleaseWait
              : isLogin
                ? $i18n.t.value.login.signIn
                : $i18n.t.value.login.createAccount
          }}
        </Button>
      </form>

      <div v-if="providers.length" class="space-y-2">
        <!--
          「OR CONTINUE WITH」那条分隔（上游 `(auth)/login/page.tsx:314`）。
          本仓此前直接从表单跳到 SSO 按钮：读屏器听不出这几颗按钮换了一条登录路径，
          视觉上也没有断点。**对照台账看不见它**——`/login` 的对照夹具里没有 SSO
          provider，这一整块根本不渲染（线索 114）。

          结构照抄：一条绝对定位的横线垫底，文字浮在中间并用背景色把线切开。
        -->
        <div class="relative">
          <div class="absolute inset-0 flex items-center">
            <span class="w-full border-t" />
          </div>
          <div class="relative flex justify-center text-xs uppercase">
            <span class="bg-background text-muted-foreground px-2">
              {{ $i18n.t.value.login.orContinueWith }}
            </span>
          </div>
        </div>
        <p v-if="showSsoHint" class="text-muted-foreground text-center text-sm">
          {{ $i18n.t.value.login.ssoHint }}
        </p>
        <Button
          v-for="provider in providers"
          :key="provider.id"
          type="button"
          variant="outline"
          class="w-full"
          :disabled="loading"
          @click="startSso(provider)"
        >
          {{ $i18n.t.value.login.continueWith(provider.display_name) }}
        </Button>
      </div>
      <!--
        上游把它包在 `div.text-center.text-sm` 里、按钮本身是**行内**的
        （login/page.tsx:347）。本仓原来给按钮加了 `w-full`，于是热区从 204px
        撑到整行 382px——点空白处也会切换登录/注册。
      -->
      <div v-if="signupAllowed" class="text-center text-sm">
        <button
          type="button"
          class="text-blue-500 hover:underline"
          @click="
            isLogin = !isLogin;
            error = '';
            showSsoHint = false;
          "
        >
          {{
            isLogin
              ? $i18n.t.value.login.noAccountSignUp
              : $i18n.t.value.login.haveAccountSignIn
          }}
        </button>
      </div>
      <!--
        同理：上游是 `div.text-muted-foreground.text-center.text-xs` 包一个行内
        `<Link class="hover:underline">`（login/page.tsx:362）。本仓原来把
        `block` 与配色都堆在链接自己身上，热区同样撑满整行。
      -->
      <div class="text-muted-foreground text-center text-xs">
        <NuxtLink to="/" class="hover:underline">{{
          $i18n.t.value.login.backToHome
        }}</NuxtLink>
      </div>
    </section>
  </div>
</template>

<style scoped>
.auth-grid {
  background-image: radial-gradient(
    circle,
    color-mix(in srgb, currentColor 35%, transparent) 1px,
    transparent 1px
  );
  background-size: 8px 8px;
  mask-image: radial-gradient(circle at center, black, transparent 70%);
}
</style>
